name: R

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    timeout-minutes: 60
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Conda installation
        uses: conda-incubator/setup-miniconda@v3
        with:
          miniconda-version: "latest"
          use-only-tar-bz2: true  # IMPORTANT: This needs to be set for caching to work properly!
          auto-update-conda: true
          auto-activate-base: true
          activate-environment: arnaq_1.0
          environment-file: inst/extdata/ARNAQ_env_1.0.yml
