name: R

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    timeout-minutes: 60
    runs-on: macos-latest
    strategy:
      matrix:
        r-version: ['4.1.1']

    steps:
      - uses: actions/checkout@v4
      - name: Set up R ${{ matrix.r-version }}
        uses: r-lib/actions/setup-r@f57f1301a053485946083d7a45022b278929a78a
        with:
          r-version: ${{ matrix.r-version }}
      - name: Set up pandoc
        uses: r-lib/actions/setup-pandoc@v2
        with:
          pandoc-version: '3.4' # The pandoc version to download (if necessary) and use.
      - run: echo "# Test" | pandoc -t html
      - name: Install dependencies
        run: |
          install.packages(c("remotes", "rcmdcheck"))
          remotes::install_deps(dependencies = TRUE)
        shell: Rscript {0}
      - name: Check
        run: rcmdcheck::rcmdcheck(args = "--no-manual", error_on = "error")
        shell: Rscript {0}
